name: Build
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Build accname
        run: npm install
        run: npm run build

      - name: Build validation
        run: npm install
        run: npm run build
        working-directory: ./validation
